yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow"
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Название",
        help_text="Введите название группы"
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="Адрес страницы группы",
        help_text="Введите адрес для страницы группы",
    )
    description = models.TextField(
        verbose_name="Описание", help_text="Введите описание группы"
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name="Текст",
        help_text="Введите текст поста"
    )
    pub_date = models.DateTimeField(
        verbose_name="Дата публикации",
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        related_name="posts",
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        Group,
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
        related_name="posts",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    image = models.ImageField(
        verbose_name="Картинка",
        upload_to="posts/",
        blank=True)

    class Meta:
        ordering = ["-pub_date", "-id"]

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="Пост",
        related_name="comment",
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        related_name="comment",
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        verbose_name="Текст",
        help_text="Напишите комментарий")
    created = models.DateTimeField(
        verbose_name="Дата публикации",
        auto_now_add=True,
    )

    class Meta:
        ordering = ["-created", "-id"]

    def __str__(self):
        return self.text[:30]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name="Подписчик",
        related_name="follower",
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        related_name="following",
        on_delete=models.CASCADE,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"],
                name="unique_following",
            )
        ]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        help_texts = {
            "text": "Вырази здесь свою душу",
            "group": "Выберите группу",
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        help_texts = {
            "text": "Не стесняйся, озвучь свое мнение 💩",
        }

yatube/posts/views.py
from functools import wraps

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.template.response import TemplateResponse
from django.views.decorators.cache import cache_page
from yatube.settings import CACHE_TIMEOUT

from .forms import CommentForm, PostForm  # isort:skip
from .models import Follow, Group, Post


def add_pagination(objects_num=settings.PAGINATION_OBJECTS_NUM):
    """Декоратор для добавления пагинации"""

    def decorator(func):
        @wraps(func)
        def wrapper(request, *args, **kwargs):
            response = func(request, *args, **kwargs)
            obj = response.context_data.pop("obj")

            paginator = Paginator(obj, objects_num)
            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)

            response.context_data["page_obj"] = page_obj
            return response.render()

        return wrapper

    return decorator


@cache_page(CACHE_TIMEOUT, key_prefix="index_page")
@add_pagination()
def index(request):
    posts = Post.objects.all()
    return TemplateResponse(request, "posts/index.html", {"obj": posts})


@add_pagination()
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()

    context = {
        "group": group,
        "obj": posts,
    }
    return TemplateResponse(request, "posts/group_list.html", context)


@add_pagination()
def profile(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    posts = user.posts.all()

    context = {
        "author": user,
        "obj": posts,
        "is_author": user != request.user,
    }

    if request.user.is_authenticated:
        following_exist = request.user.follower.filter(author=user).exists()
        context["following"] = following_exist

    return TemplateResponse(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comment.all()
    comment_form = CommentForm(request.POST or None)

    context = {
        "post": post,
        "comment_form": comment_form,
        "comments": comments,
        "is_author": post.author == request.user,
    }

    return render(request, "posts/post_detail.html", context=context)


@login_required
def post_create(request):
    user = request.user

    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(False)
        post.author = user
        post.save()
        return redirect("posts:profile", user.username)

    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user

    if post.author != user:
        return redirect("posts:post_detail", post_id)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)

    context = {"form": form, "is_edit": True}
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
@add_pagination()
def follow_index(request):
    following_ids = request.user.follower.values_list("author", flat=True)
    posts = Post.objects.filter(author_id__in=following_ids)
    return TemplateResponse(request, "posts/index.html", {"obj": posts})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(get_user_model(), username=username)

    if request.user == author:
        return redirect("posts:profile", username=username)

    Follow.objects.get_or_create(user=request.user, author=author)

    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    following = request.user.follower.filter(author__username=username).first()

    if following:
        following.delete()

    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">

      <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Новый пост
          {% endif %}
      </div>

      <div class="card-body">
        {% include 'includes/error_form.html' %}

        <form method="post" enctype="multipart/form-data"
          {% if action_url %}
              action="{% url 'action_url' %}"
          {% endif %}
        >
          {% csrf_token %}
          {% include 'includes/for_form.html' %}

          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}Ваши подписки{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 follow_index_page %}
    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %} Записи сообщества {{ group.title }} {% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>

  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Пост {{ post.text|truncatechars:30 }}  {% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}

          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
        {% if is_author %}
          <li class="list-group-item">
            <a href="{% url 'posts:post_edit' post.id %}">
              Редактировать пост
            </a>
          </li>
        {% endif %}
      </ul>
    </aside>

    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if user.is_authenticated %}
        {% include 'posts/includes/comment_create.html' %}
      {% endif %}
      {% include 'posts/includes/comments_display.html' %}
    </article>

  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}Профайл пользователя {{ author.username }}{% endblock %}

{% block content %}
  <h1>Все посты пользователя {{ author.username }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  {% if user.is_authenticated  and is_author %}
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
  {% endif %}

  {% cache 20 profile_page %}
    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}