yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("only_user/", views.only_user_page, name="only_user"),
    path("only_anon/", views.only_anon_page, name="only_anon"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.MyLogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        views.MyPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.MyPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        views.MyPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

yatube/users/views.py
from core.check_access import only_anon_view
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView

from .forms import CreationForm


def only_user_page(request):
    return render(request, "users/check_anon.html")


def only_anon_page(request):
    return render(request, "users/check_authenticated.html")


@method_decorator(only_anon_view, name="dispatch")
class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"


@method_decorator(only_anon_view, name="dispatch")
class MyLoginView(auth_views.LoginView):
    template_name = "users/login.html"


class MyLogoutView(auth_views.LogoutView):
    template_name = "users/logged_out.html"


@method_decorator(only_anon_view, name="dispatch")
class MyPasswordResetView(auth_views.PasswordResetView):
    template_name = "users/password_reset_form.html"
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")


@method_decorator(only_anon_view, name="dispatch")
class MyPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = "users/password_reset_confirm.html"
    success_url = reverse_lazy("users:password_reset_complete")


@method_decorator(login_required, name="dispatch")
class MyPasswordChangeView(auth_views.PasswordChangeView):
    template_name = "users/password_change_form.html"
    success_url = reverse_lazy("users:password_change_done")

yatube/templates/users/check_anon.html
{% extends "base.html" %}

{% block title %}Вы не авторизованы{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">

      <div class="card">
        <div class="card-header">Вы не авторизованы （⊙ｏ⊙）</div>
        <div class="card-body">
          <p>
            Доступ к этой странице только у авторизованных пользователей<br>
            <a href="{% url 'users:login' %}">Войти</a>
          </p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/check_authenticated.html
{% extends "base.html" %}

{% block title %}Вы авторизованы{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">

    <div class="card">
      <div class="card-header">Вы авторизованы</div>
      <div class="card-body">
        <p>
          Эту страницу могут видеть только не авторизованные пользователи<br>
          <a href="{% url 'users:logout' %}">Выйти</a>
        </p>

      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">

    <div class="card">
      <div class="card-header">Выход</div>

      <div class="card-body">
        <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
      </div>
    </div>

  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти на сайт{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Войти на сайт</div>

      <div class="card-body">
        {% include 'includes/error_form.html' %}

        <form method="post"
          {% if action_url %}
              action="{% url 'action_url' %}"
          {% endif %}
        >
          {% csrf_token %}

          {% include 'includes/for_form.html' %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>

        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}

{% block title %}Пароль изменён{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">

    <div class="card">
      <div class="card-header">Пароль изменён</div>

      <div class="card-body">
        <p>Пароль изменён успешно</p>
      </div> <!-- card body -->
    </div> <!-- card -->

  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}

{% block title %}Изменение пароля{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Изменить пароль</div>

      <div class="card-body">
      {% include 'includes/error_form.html' %}

        <form method="post"
          {% if action_url %}
              action="{% url 'action_url' %}"
          {% endif %}
        >
          {% csrf_token %}

          {% include 'includes/for_form.html' %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пароль
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">

    <div class="card">
      <div class="card-header">Восстановление пароля завершено</div>

      <div class="card-body">
        <p>Ваш пароль был сохранен. Используйте его для входа</p>
        <a href="{% url 'users:login' %}">Войти</a>
      </div>

    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Новый пароль{% endblock %}

{% block content %}
{% if validlink %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Введите новый пароль</div>

        <div class="card-body">
        {% include 'includes/error_form.html' %}

          <form method="post"
            {% if action_url %}
                action="{% url 'action_url' %}"
            {% endif %}
          >

            {% csrf_token %}

            {% include 'includes/for_form.html' %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>

          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">

        <div class="card-header">Ошибка</div>

        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->

      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Отправлено письмо</div>

      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для
          восстановления пароля</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Чтобы сбросить старый пароль — введите адрес электронной почты,
        под которым вы регистрировались
      </div>

      <div class="card-body">
        {% include 'includes/error_form.html' %}

        <form method="post" action="{% url 'users:password_reset' %}">
          {% csrf_token %}

          {% include 'includes/for_form.html' %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Сбросить пароль
            </button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>

      <div class="card-body">
        {% include 'includes/error_form.html' %}

        <form method="post" action="{% url 'users:signup' %}">
          {% csrf_token %}

          {% include 'includes/for_form.html' %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div> <!-- card body -->

    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}